server
{
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/
    {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 60s;
    }

    location /css/
    {
        alias /frontend/css/;
    }

    location /js/
    {
        alias /frontend/js/;
    }

    location /auth/css/
    {
        alias /frontend/auth/css/;
    }

    location /auth/js/
    {
        alias /frontend/auth/js/;
    }

    location /auth/
    {
        alias /frontend/auth/html/;
        try_files $uri $uri/ =404;
    }

    location /
    {
        try_files $uri $uri/ /index.html;
    }
}